version: '3'
services:
  web:
    build: .
    ports:
      - "8080:80"
  mysql:
    image: mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=vufind
    volumes:
      - ./module/VuFind/sql/mysql.sql:/docker-entrypoint-initdb.d/mysql.sql